### ISSUE TITLE
Async display of contents (also AsyncSeq)

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#104] opened 2016-12-02 12:46 UTC
Question for @cgravill, @tpetricek @sylvanc  - is it technically feasible to have ``Async`` values display asynchronously in the Jupyter display?  I presume Javascript would have to be injected which polls the server, and that this might be a modification of the Jupyter protocol beyond the scope of iFSharp directly?

If we could do this, I would then ask whether it's possible to have ``AsyncSeq`` values display as animated sequences, where each element updates the DOM element with replacement Javascript

**Comment by cgravill** [comment] 2016-12-02 14:27
@tpetricek mentioned the bonus feature in #96 that you can do on-demand fetching so parts of this may now be present.

**Comment by cgravill** [comment] 2018-07-06 10:06
@dgrechka the Jupyter Comms may be useful for this: http://jupyter-notebook.readthedocs.io/en/stable/comms.html

**Comment by dgrechka** [comment] 2018-07-06 12:04
@cgravill Thank you! Indeed, Comms may better fit here rather than establishing separate communication channel. I'll try them.
Supporting Comms by the kernel side is also a step towards #126

**Comment by dgrechka** [comment] 2018-07-10 12:40
I found that Jupyter protocol v5.1 supports [updating of display outputs](https://jupyter-client.readthedocs.io/en/stable/messaging.html#update-display-data) from kernel side.

Although it requires update the protocol from 4.0 to at least 5.1

Maybe that will be enough to achieve differed results display. I'm trying it right now.

**Comment by dgrechka** [comment] 2018-07-10 16:18
@dsyme  FYI, I managed to get some working results for `Async` values display.

The demo link:
[![Demo](https://img.youtube.com/vi/zMZqo2P6j5c/0.jpg)](https://www.youtube.com/watch?v=zMZqo2P6j5c).

When the Async is displayed it is started as a task on a separate thread. Upon result readiness the corresponding output is updated.
The approach uses protocol's v5.1 `update_display_data` messages. Neither JS injection nor protocol extension is required.

Don't know whether the active async computation should mark the kernel as busy... Right now it does not.

I need some further testing and code cleanup, and then I'll create a PR.

**Comment by cgravill** [comment] 2018-07-10 18:40
That looks like a great start. Is the plan to get Async of a single value first then see if AsyncSeq is possible afterwards?

**Comment by dgrechka** [comment] 2018-07-11 08:58
Yes. The plan is to make several small incremental changes, delivering some value.
They are easier to review. Async of single value is the fist step.

**Comment by dsyme** [comment] 2018-08-02 11:09
Wow, this is fantastic

**Comment by dgrechka** [comment] 2018-08-02 11:12
Thank you!
I'm implementing AsyncSeq display right now...

**Comment by dgrechka** [comment] 2018-08-07 08:45
The asyncSeq display prototype is ready!

The demo link:
[![Demo](https://img.youtube.com/vi/ShH7whL57iU/0.jpg)](https://www.youtube.com/watch?v=ShH7whL57iU).

Now I'm cleaning up the code and will do PR to close the issue.

**Comment by cgravill** [comment] 2018-08-07 09:06
That's very nice!

Will this be compatible with Angara Charting as well and so we can have e.g. simulator creating results and progressively display results?

**Comment by dgrechka** [comment] 2018-08-07 11:01
Right now it appends the output upon fetching next element from asyncSeq.

What I can propose for now (in the situation of limited time) is to provide a switch which toggles the  AsyncSeq display modes.

The modes:

1) Replacing the recent produced element upon next element readiness 
1) Appending the next produced element to the output (accumulating elements)

For the use case of updating the charts, we can activate display mode (1) and produce AsyncSeq<Chart>

It has disadvantage of possible chart blinking and visible region reset as the chart is entirely replaced, but this  approach is more feasible to get the usable results in time.

The approach also have advantages:

This can be useful not only for the charts, but for outputting of some recent text statuses, e.g. recent text summary of some long running parameter inference process.

It is also type agnostic in a sense that it will update any type of output (different charting libraries, custom printers supported)

If such chart updates turn out to be inconvenient in practice, we can implement chart library specific data updates, maybe as separate github issue.

What do you think?

**Comment by cgravill** [comment] 2018-08-07 13:13
That makes sense, you're note making a `AsyncSeq<Data>` and feeding to `Chart`. I can see how that makes it specific.

What syntax do you think is possible? If its a per invocation that seems OK. It's potentially awkward if it's a global state latch.

If the calculations are fairly granular, then redrawing the chart is likely to be OK.

Longer term something with a virtual DOM (e.g. https://github.com/elmish/elmish) with differential updates might make sense, but that's out of scope of this.

**Comment by dgrechka** [comment] 2018-08-08 13:29
Now I think that it is more convenient to see the latest single value of AsyncSeq by default.
There are more use cases for this.
And for the case of accumulation all of the AsyncSeq elements on a screen we can add special call like
```
asyncSeq {... } |> DisplayAllElements
```

I did some experimenting with showing a recent value of AsyncSeq.
While the text updates are fine (e.g. time value updates in the demo below), the chart blinks and resizes terribly!

Tried to build a demo for the linear regression MCMC parameter inference with updating charts:
[![Demo](https://img.youtube.com/vi/_oIlRZ-DN1o/0.jpg)](https://www.youtube.com/watch?v=_oIlRZ-DN1o).

I'm considering building some Angara.Charting specific code to update the data without the replacement of the chart. From the user point of view it can be the way you proposed, something like `AsyncSeq<Data> |> Chart.ofLiveData`

**Comment by dgrechka** [comment] 2018-08-08 16:34
@dsyme Being the initial creator of the issue what do you expect from AsyncSeq display?

* Displaying all of the pulled elements one by one, accumulating them on screen?
* Displaying the recently pulled element?
* Updating the data inside the charts?

What is your use case?

**Comment by cgravill** [comment] 2018-08-09 10:54
A lot of the UI blinking is caused by going from:

Empty
State at time 1
Empty
State at time 2

I'm not sure how much control we have in the Jupyter context but would it be possible to avoid these intermediate steps, or say reserve the previous size? Potentially document fragments would help https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment ? I've used that on other projects to avoid the cost of intermediate reflows.

**Comment by dgrechka** [comment] 2018-08-14 15:43
I created dynamically updated Angara.charts prototype.

[![Demo](https://img.youtube.com/vi/DZjZ4tYjoG8/0.jpg)](https://www.youtube.com/watch?v=DZjZ4tYjoG8).

Cleaning up the code for pull requesting...

**Comment by cgravill** [comment] 2018-08-16 13:15
Looks really promising.

The trade-off seems OK for initial support: by default work OK for test etc. but for animated plotting you have to do a little library specific effort.

**Comment by dsyme** [comment] 2018-08-23 16:02
This is amazing! :)

**Comment by cgravill** [comment] 2019-02-24 11:35
I think this issue is complete in terms of original scope. There's a very cool example from @SpaceAntelope of what this feature enabled:
https://areslazarus.com/archive/cntk-102-hidden-layers-live-progress-report-widget/

**Closed by cgravill** 2019-02-24 11:35 UTC
Labels: question
