### ISSUE TITLE
Issues while trying out samples

### ISSUE THREAD

**Issue by forki** [fsprojects/IfSharp#155] opened 2017-10-06 15:49 UTC
@jdh30 reported issues with the azure notebook samples on Twitter: https://twitter.com/jonharrop/status/916312696458502144

I just report it here so that contributors know about it and may check if samples are still up-to-date

**Comment by cgravill** [comment] 2017-10-07 10:35
I'm guessing it's this one https://twitter.com/jonharrop/status/916313349272621056

This is working for me:

1. https://notebooks.azure.com/
2. Choose the Introduction to F#
3. Clone
4. Run the relevant cells at the end of the notebook

![image](https://user-images.githubusercontent.com/1099725/31306934-377598ec-ab52-11e7-9e14-a3dda5bac40b.png)

https://notebooks.azure.com/cgravill/libraries/fsharp_test/html/FSharp%20for%20Azure%20Notebooks.ipynb

Note the preview will not show the hovering circle and instead the the HTML. This is a by-design Jupyter security behaviour:
http://jupyter-notebook.readthedocs.io/en/stable/security.html#our-security-model 

There are potential safe ways around this.

@jdh30 can you provide any more details on the original bug please?

**Comment by cgravill** [comment] 2017-10-07 11:28
On the original tweet, we're demonstrating interactive D3 hence it being long. If someone just wants to draw a circle they can do something shorter:

![image](https://user-images.githubusercontent.com/1099725/31307334-53e5c1ca-ab5a-11e7-8210-f2c154b6c0fa.png)

we should probably make Bitmap types display automatically so the imageToByteArray isn't needed. For various reasons, we tend to work with SVGs which is what this has already been done for.

**Comment by jdh30** [comment] 2017-10-07 12:19
No, it was this one:

https://twitter.com/jonharrop/status/916313349272621056

https://pbs.twimg.com/media/DLdmEYIW0AAO8lx.png

https://pbs.twimg.com/media/DLdmFsoWkAYeipG.png

I did exactly what you said (choose F# Intro, Clone, Kernel->Run all).

**Comment by dsyme** [comment] 2017-10-07 13:00
@cgravill   - I can repro the bug by cloning the notebook https://notebooks.azure.com/cgravill/libraries/fsharp_test/html/FSharp%20for%20Azure%20Notebooks.ipynb

Mono version is showing as 5.0.1.1 - I recall a Mono bug that has been fixed in early 5.0.x.  I think we should update to 5.2 or 5.4,  I tried to use the in-browser terminal (click on Jupyter to left of notebook --> "New" -> "Terminal") to update a running kernel (it should be possible?) but didn't have the nbuser sudo password or the docker image - is it public?

![image](https://user-images.githubusercontent.com/7204669/31308062-bfe24792-ab67-11e7-94d6-298ade7e7b30.png)

**Comment by dsyme** [comment] 2017-10-07 13:01
@jdh30 Thanks or the bug report - we evidently didn't re-validate the notebook after a Mono update

**Comment by cgravill** [comment] 2017-10-07 13:08
Thanks @jdh30 that clarifies where the issue is - I was testing later in the notebook based in the initial report. I can reproduce the error in the online Azure Notebooks. It doesn't occur in a local IfSharp Windows install so it'll need digging into.

**Comment by cgravill** [comment] 2017-10-07 13:22
@dsyme Mono 5.2.* looks promising as a fix.

On Mac OS:
```
Mono JIT compiler version 5.2.0.224 (d15-3/14f2c81 Thu Aug 24 10:33:52 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen (concurrent by default)
```

The relevant code complete successfully:

```fsharp
type MyType = { FirstName: string; LastName: string }
let records = 
    [|
        { FirstName = "Walter"; LastName = "Harp" }
        { FirstName = "Jeff"; LastName = "Smith" }
        { FirstName = "Ben"; LastName = "Smith" }
        { FirstName = ""; LastName = "Holly" }
    |]

records |> Util.Table
```

**Comment by cgravill** [comment] 2017-10-07 13:28
@dsyme there looks to be a way of getting privileges here https://github.com/Microsoft/AzureNotebooks/issues/112 (I've not tried it as it looks involved...)

**Comment by cgravill** [comment] 2017-10-28 14:42
Mono 5.2.0.224 is deployed to Azure Notebooks, and I've validated it there. Let us know if more issues come up.

**Closed by cgravill** 2017-10-28 14:42 UTC
